import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Child from "@/components/layout/child";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Child>{children}</Child>
            </body>
        </html>
    );
}
